### PR TITLE
Fix for Python3.11

### LINKED ISSUE #49: Python 3.11 Compatibility
checkout the following:  https://github.com/unk2072/single-beat/commit/74992b371e0326cf790bdf991e0ec58e43440864

It's needed to truly work with Python 3.11

### PR DESCRIPTION
**Pull request by unk2072**
Fixed some errors when combined with Python 3.11.
The modified code seems to work fine in my environment.

fixes #49

### CODE REVIEW

**Comment by ybrs** [comment]
@cpressland Sorry. Merged, tested and made a new pypi release. Thanks for your contribution.

**Comment by cpressland** [comment]
Thanks @ybrs! Appreciate it, and thank you @unk2072 for the actual work 👍

**Comment by k-aziz** [comment]
@ybrs It doesn't look like the latest pypi release includes the fix. Still running into the issue with version 0.6.2, and looking at the source files on pypy it doesn't look like the requirements have changed in setup.py:

```
    install_requires=[
        'redis >= 2.9.1',
        'aioredis >= 2.0',
        'Click>=7.0'
    ],
```

**Comment by ybrs** [comment]
@k-aziz I think it was due to some local configuration on my end for releasing. Sorry about that. I just bumped version and re-released. Could you please try it again.

**Comment by k-aziz** [comment]
Working now. Thanks for the quick response.

**Pull request merged**
